# Git Webhook Container Configuration

# Define workflows first
workflows:
  production:
    description: "Production workflow - pull only, reset local changes"
    reset_on_changes: true
    pull: true
    commit: false
    push: false
    submodule_update: true
    submodule_remote: false
    submodule_commit_push: false

  development:
    description: "Development workflow - full sync with commit and push"
    reset_on_changes: false
    pull: true
    commit: true
    push: true
    submodule_update: true
    submodule_remote: true
    submodule_commit_push: true

  staging:
    description: "Staging workflow - pull and commit, but no push"
    reset_on_changes: false
    pull: true
    commit: true
    push: false
    submodule_update: true
    submodule_remote: true
    submodule_commit_push: false

# Container configurations
containers:
  - id: "34bee3f5-fb2b-4bab-b45e-c303b1d15137"
    name: "prod-server-1"
    branch: "main"
    workflow: "production"
    repos_dir: "/home/container/server-data"
    submodules:
      - path: "resources/[VL_Scripts]/[Cars]"
        branch: "main"
      - path: "resources/[VL_Scripts]/[Core]"
        branch: "main"

  - id: "fbb6360b-1f8f-4768-a39e-340daf0eac6f"
    name: "dev-server-1"
    branch: "dev"
    workflow: "development"
    repos_dir: "/home/container/server-data"
    submodules:
      - path: "resources/[VL_Scripts]/[Cars]"
        branch: "dev"
      - path: "resources/[VL_Scripts]/[Weapons]"
        branch: "dev"
      - path: "resources/[UI]/[Components]"
        branch: "dev"

  - id: "51c6374c-c9ff-49bb-90b8-c68d1326fabe"
    name: "dev-server-2"
    branch: "dev"
    workflow: "development"
    repos_dir: "/home/container/server-data"
    submodules:
      - path: "resources/[VL_Scripts]/[Cars]"
        branch: "dev"

  - id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
    name: "staging-server"
    branch: "staging"
    workflow: "staging"
    repos_dir: "/home/container/server-data"
    submodules:
      - path: "resources/[VL_Scripts]/[Cars]"
        branch: "staging"

# Global settings (can be overridden by environment variables)
settings:
  default_repos_dir: "/home/container/server-data"
  commit_message_template: "Auto-commit by webhook: {timestamp}"
  max_concurrent_containers: 5
  container_timeout: 300
